### ISSUE TITLE
tag limit

### ISSUE THREAD

**Issue by lisam1980** [mokhin-denis/mod_my_cloud#1]
Hi, i'm not sure how I missed it, but is there a way to limit the number of tags the module shows? I want it to process all content but only show a certain number of tags. Is that possible? If I limit content processed, nothing shows up. Thank you in advance for any help!

**Comment by mokhin-denis** [comment]
There are 2 ways to limit the number of tags:
1. You can set "Number of content items to process" (0 - no limits) or
2. You can hide tags with the pointed rank and lower
