### ISSUE TITLE
The tags are not appearing

### ISSUE THREAD

**Issue by ynatividade** [mokhin-denis/mod_my_cloud#2]
Dear developer,
My module doesn't show the article's tags...
I really wanna to make it works well. Can you help me?
Please, forgive the message on your facebook, I didn't saw this issues page.
Thanks in advance!

**Comment by mokhin-denis** [comment]
Maybe you articles dont have meta-kewords?

**Comment by ynatividade** [comment]
No, mokhin-denis, I put tags in some articles to teste and.... nothing...
Another sugestion?

**Comment by mokhin-denis** [comment]
Lets start from beginning:
1. Do you use the latest version of Joomla? Latest version of plugin?
2. Try to use default settings
3. Did you publish your module? Can you set and see the title of module?
2. Is your website multilingual?
