### ISSUE TITLE
Tag how chose a article, how chose the limite ?

### ISSUE THREAD

**Issue by ZerooCool** [mokhin-denis/mod_my_cloud#3]
How i can install Jquery for this module ?

**Comment by mokhin-denis** [comment]
You dont need any JQuery or other JS framework for work with this Joomlas Module. Just use metakewords in your articles.

**Comment by ZerooCool** [comment]
Ok but, i see a lot word, i can't stop 10 other 20 word only, i see only TEXT MODE.

**Comment by mokhin-denis** [comment]
Sorry... dont get, what you mean...

**Comment by ZerooCool** [comment]
Sorry for my question.

You can see : https://www.visionduweb.eu
I search if i can limit the number of keyword.

**Comment by mokhin-denis** [comment]
You should have much more, than one keyword. So you can limit cloud words by limit the minimum number (weight) of keyword

**Comment by ZerooCool** [comment]
Yes i have a lot keywords. I want limited 20 or 40 keywords only.
If it's possible ?

**Comment by mokhin-denis** [comment]
Think that way: what are keywords is need to show? There is no way to some keywords show, and some hide. But if there is a lot content with one keyword - that keyword has a bigger weight and size. You can show it in brackets, or as a power of keyword. So in that way you can limit and show keywords start from any weaight you want

**Comment by ZerooCool** [comment]
Ok, i use the black list, and, it's ok. I can now remove keywords.
