### ISSUE TITLE
Error message on new install, Joomla 3.6.4

### ISSUE THREAD

**Issue by vickythomas** [mokhin-denis/mod_my_cloud#4]
I just installed MyCloud module, v 0.12 on J3.6.4 site.  Looks great, thank you, with great styling options!  But when I choose a 'tag' and go to the results page, this error shows on the module itself 

> Notice: Trying to get property of non-object in /x/public_html/modules/mod_my_cloud/mod_my_cloud.php on line 71

**Comment by mokhin-denis** [comment]
Its just a notice and you should not show notice on your production site. Switch notices of in your php.ini or .htaccess file.

**Comment by vickythomas** [comment]
OK, yes I did turn off error messages. But didn't know you knew about this message.  Sincerely, VIcky

**Comment by mokhin-denis** [comment]
Thank you a lot! I'll check it out.
