### ISSUE TITLE
excluded categories displayed in results, also is search based on keyword?

### ISSUE THREAD

**Issue by vickythomas** [mokhin-denis/mod_my_cloud#5]
Hi, I excluded some categories, but these articles still show in the results.  Attached is screenshot of mod settings, and results.  

![mycloud module settings exclude categories](https://cloud.githubusercontent.com/assets/8184561/21145404/1ee69356-c11c-11e6-9e10-c18e23c2cbbc.JPG)

Category 99 is 'Sneak Peak Videos'.  After I excluded this, I still see articles from this category. 
![mycloud module settings exclude categories showing](https://cloud.githubusercontent.com/assets/8184561/21145405/1ee97cd8-c11c-11e6-9a29-7bababfde4c2.JPG)
Yes, I cleared the server cache and browser cache, several times.

I am also confused, because (see second screenshot) this article was returned in results after I clicked on Cloud label "Jedi"  even though "Jedi" is not a keyword for this article.  I thought the module only returned articles based on keyword.

Can you confirm if setting are correct, and mode of results based on clicking on MyCloud keyword?  Thanks. I did update to latest version today.  But the issues is the same.  SIncerely, Vicky

**Comment by vickythomas** [comment]
Update:  I may have figured out a few things.  MyCloud exclusions are most likely applied to where to pull keywords from, and not related to search results ... is that correct?

I have confirmed (as I still have the J2.5 site avail), that the module I used there, Taxonomy Cloud, returned all (and only) articles with keywords that equal whatever keyword they clicked on in the Module.

I think I thought your module used the same logic (and thankfully worked on J3 sites), but the articles returned when keywords on MyCloud are clicked are not the same results ... these include additional articles beyond only those with that keyword.  Is that the design?  Is there a way I can modify and change a setting so that we see ONLY the articles that we've placed that keyword in?

Thanks, Vicky

**Comment by mokhin-denis** [comment]
Okay, let me explain. You put keywords in article. You put article in category. When you point, which category include or exclude - it just for MyTags Cloud only. And when you click on tag (read: keyword), it just opens searchpage, that is. There is no any componet using for search by tags. Use Joomlas tags instead for it.

**Comment by vickythomas** [comment]
Thank you.  That explains it nicely.  I misunderstood how the MyCloud module responded when a keyword in the cloud was clicked.  Thank you for making this very nice module available to the public.
Sincerely, Vicky Thomas

**Comment by mokhin-denis** [comment]
Adding a review at [JED](https://extensions.joomla.org/extensions/extension/search-a-indexing/tags-a-clouds/mycloud) is the best way to say thanks ))

**Comment by vickythomas** [comment]
Hi, I tried to leave a review today, but clicking 'write a review' on this page
https://extensions.joomla.org/extensions/extension/search-a-indexing/tags-a-clouds/mycloud
sends me to the JED home page instead.  
Not sure what is going on, I will try again.  Sincerely, Vicky
